/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { RoomService } from "../room.service";
import { RoomCreateInput } from "./RoomCreateInput";
import { Room } from "./Room";
import { RoomFindManyArgs } from "./RoomFindManyArgs";
import { RoomWhereUniqueInput } from "./RoomWhereUniqueInput";
import { RoomUpdateInput } from "./RoomUpdateInput";
import { ColumnFindManyArgs } from "../../column/base/ColumnFindManyArgs";
import { Column } from "../../column/base/Column";
import { ColumnWhereUniqueInput } from "../../column/base/ColumnWhereUniqueInput";
import { StageFindManyArgs } from "../../stage/base/StageFindManyArgs";
import { Stage } from "../../stage/base/Stage";
import { StageWhereUniqueInput } from "../../stage/base/StageWhereUniqueInput";

export class RoomControllerBase {
  constructor(protected readonly service: RoomService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Room })
  async createRoom(@common.Body() data: RoomCreateInput): Promise<Room> {
    return await this.service.createRoom({
      data: data,
      select: {
        createdAt: true,
        guid: true,
        id: true,
        name: true,
        updatedAt: true,
        users: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Room] })
  @ApiNestedQuery(RoomFindManyArgs)
  async rooms(@common.Req() request: Request): Promise<Room[]> {
    const args = plainToClass(RoomFindManyArgs, request.query);
    return this.service.rooms({
      ...args,
      select: {
        createdAt: true,
        guid: true,
        id: true,
        name: true,
        updatedAt: true,
        users: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Room })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async room(
    @common.Param() params: RoomWhereUniqueInput
  ): Promise<Room | null> {
    const result = await this.service.room({
      where: params,
      select: {
        createdAt: true,
        guid: true,
        id: true,
        name: true,
        updatedAt: true,
        users: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Room })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateRoom(
    @common.Param() params: RoomWhereUniqueInput,
    @common.Body() data: RoomUpdateInput
  ): Promise<Room | null> {
    try {
      return await this.service.updateRoom({
        where: params,
        data: data,
        select: {
          createdAt: true,
          guid: true,
          id: true,
          name: true,
          updatedAt: true,
          users: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Room })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteRoom(
    @common.Param() params: RoomWhereUniqueInput
  ): Promise<Room | null> {
    try {
      return await this.service.deleteRoom({
        where: params,
        select: {
          createdAt: true,
          guid: true,
          id: true,
          name: true,
          updatedAt: true,
          users: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/columns")
  @ApiNestedQuery(ColumnFindManyArgs)
  async findColumns(
    @common.Req() request: Request,
    @common.Param() params: RoomWhereUniqueInput
  ): Promise<Column[]> {
    const query = plainToClass(ColumnFindManyArgs, request.query);
    const results = await this.service.findColumns(params.id, {
      ...query,
      select: {
        createdAt: true,
        guid: true,
        id: true,
        name: true,
        position: true,

        room: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/columns")
  async connectColumns(
    @common.Param() params: RoomWhereUniqueInput,
    @common.Body() body: ColumnWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      columns: {
        connect: body,
      },
    };
    await this.service.updateRoom({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/columns")
  async updateColumns(
    @common.Param() params: RoomWhereUniqueInput,
    @common.Body() body: ColumnWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      columns: {
        set: body,
      },
    };
    await this.service.updateRoom({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/columns")
  async disconnectColumns(
    @common.Param() params: RoomWhereUniqueInput,
    @common.Body() body: ColumnWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      columns: {
        disconnect: body,
      },
    };
    await this.service.updateRoom({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/stages")
  @ApiNestedQuery(StageFindManyArgs)
  async findStages(
    @common.Req() request: Request,
    @common.Param() params: RoomWhereUniqueInput
  ): Promise<Stage[]> {
    const query = plainToClass(StageFindManyArgs, request.query);
    const results = await this.service.findStages(params.id, {
      ...query,
      select: {
        createdAt: true,
        description: true,
        guid: true,
        id: true,
        name: true,
        position: true,

        room: {
          select: {
            id: true,
          },
        },

        stageOrder: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/stages")
  async connectStages(
    @common.Param() params: RoomWhereUniqueInput,
    @common.Body() body: StageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      stages: {
        connect: body,
      },
    };
    await this.service.updateRoom({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/stages")
  async updateStages(
    @common.Param() params: RoomWhereUniqueInput,
    @common.Body() body: StageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      stages: {
        set: body,
      },
    };
    await this.service.updateRoom({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/stages")
  async disconnectStages(
    @common.Param() params: RoomWhereUniqueInput,
    @common.Body() body: StageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      stages: {
        disconnect: body,
      },
    };
    await this.service.updateRoom({
      where: params,
      data,
      select: { id: true },
    });
  }
}
